import { CandidaturaAdmin } from '../types';
import { DadosInscricaoFormando } from '../../../utils/securityAndValidation';

export const converterCandidaturaAdminParaDadosFicha = (
  cand: CandidaturaAdmin
): DadosInscricaoFormando => {
  const fotoDoc = cand.documentos?.find((d) => d.tipo === 'FOTO');

  return {
    id: String(cand.id),
    protocolo: cand.codigo,
    numero_inscricao: String(cand.inscricao_id || cand.id).padStart(4, '0'),
    numero_processo: cand.processo_numero || undefined,
    ano: String(cand.ano || 2026),
    data_inscricao: cand.data_submissao || cand.data_criacao,
    nome: cand.nome,
    nome_pai: cand.nome_pai || '',
    nome_mae: cand.nome_mae || '',
    bi: cand.bi,
    arquivo_identificacao: cand.arquivo_identificacao || 'São Tomé',
    nif: cand.nif || '',
    datanascimento: cand.data_nascimento,
    idade: cand.idade ? String(cand.idade) : '',
    sexo: cand.sexo || 'Masculino',
    nacionalidade: cand.nacionalidade || 'Santomense',
    naturalidade: cand.naturalidade || 'São Tomé',
    estado_civil: cand.estado_civil || 'Solteiro(a)',
    agregado_familiar: cand.agregado || '1',
    morada: cand.morada || '',
    distrito: cand.distrito || 'Água Grande',
    telefone: cand.contacto || '',
    telefone2: cand.contacto_alternativo || '',
    email: cand.email || '',
    ocupacao: cand.ocupacao || 'Candidato a Formação',
    habilitacao_nivel: cand.habilitacao_nivel || '',
    habilitacao_classe: cand.habilitacao_classe || '',
    habilitacao_area: cand.habilitacao_area || '',
    habilitacao: cand.habilitacao_literaria || '',
    formacao_profissional: cand.formacao_profissional || '',
    experiencia_profissional: cand.experiencia_profissional || '',
    motivo_inscricao: cand.motivo_inscricao || 'Qualificação profissional e inserção no mercado de trabalho.',
    situacao_emprego: cand.situacao_emprego || 'Candidato à Procura do 1º Emprego',
    atividade_profissional_anterior: cand.atividade_profissional_anterior || '',
    funcao_exerce: cand.funcao_exerce || '',
    funcao_desde: cand.funcao_desde || '',
    profissao: cand.profissao || '',
    possui_caso_especial: cand.deficiente ? 'Sim' : 'Não',
    casos_especiais: cand.deficiente ? 'Candidato com necessidades especiais' : '',
    encaminhado_apoio_social: cand.encaminhado_apoio_social ? 'Sim' : 'Não',
    instituicao_apoio_social: cand.instituicao_apoio_social || '',
    encaminhado_outra_instituicao: cand.encaminhado_outra_instituicao || '',
    programa_id: String(cand.programa_id || 1),
    programa_nome: cand.programa?.nome || 'Qualificação Inicial',
    curso_id: String(cand.curso_opcao1_id || 1),
    curso_nome: cand.curso_opcao1?.nome || '',
    curso_horario: cand.curso_opcao1?.horario || '',
    curso_local: cand.curso_opcao1?.local_realizacao || 'CFP-STP São Tomé',
    curso_acao: cand.curso_opcao1?.acao || '',
    programa_opcao_2_id: cand.curso_opcao2?.programa_id ? String(cand.curso_opcao2.programa_id) : '',
    curso_opcao_2_id: cand.curso_opcao2_id ? String(cand.curso_opcao2_id) : '',
    curso_opcao_2_nome: cand.curso_opcao2?.nome || '',
    curso_opcao_2_programa: cand.curso_opcao2?.programa_nome || '',
    curso_opcao_2_horario: cand.curso_opcao2?.horario || '',
    curso_opcao_2_local: cand.curso_opcao2?.local_realizacao || '',
    situacao: cand.estado,
    observacao: '',
    autoriza_divulgacao_dados: cand.autorizacao_divulgacao_dados ? 'Sim' : 'Não',
    fotoPreview: fotoDoc?.download_url || '',
    aceita_declaracao: true,
  };
};
