export const defaultValues = {
    nome: '',
    numero_bi: '',
    numero_nif: '',
    numero_iban: '',
    banco: '',
    data_nascimento: '',
    estado_civil: '',
    morada: '',
    distrito: '',
    genero: '',
    habilitacao_literaria: '',
    formacao_profissional: '',
    formacao_complementar: '',
    experiencia_trabalho: '',
    area_candidatura: '',
    observacao: '',
    formacao_pedagogica: false,
    modulos: [],
    doc_bi: '',
    doc_nif: '',
    doc_habilitacoes: '',
    doc_formacao_prof: '',
    doc_formacao_comp: '',
    doc_cv: '',
    doc_experiencia: '',
    doc_outros: '',
  };
  